apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kwetterk8s-reactjs"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kwetterk8s-reactjs"
  template:
    metadata:
      labels:
        app: "kwetterk8s-reactjs"
    spec:
      containers:
        - name: "kwetterk8s-reactjs"
          image: "kwettercr.azurecr.io/kwetterk8s"
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: 20m
            limits:
              cpu: 50m
