apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kwetter-efa5"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kwetter-efa5"
  template:
    metadata:
      labels:
        app: "kwetter-efa5"
    spec:
      containers:
        - name: "kwetter-efa5"
          image: "kwetterreact.azurecr.io/kwetter"
          ports:
          - containerPort: 80