apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: "kwetterk8s-d7bc"
spec:
  maxReplicas: 6 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "kwetterk8s-d7bc"
  targetCPUUtilizationPercentage: 50 # target CPU utilization
