apiVersion: v1
kind: Service
metadata:
    name: "kwetterk8s-d7bc"
    labels:
        app: "kwetterk8s-d7bc"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kwetterk8s-d7bc"