# This is a basic workflow that is manually triggered
name: EndToEnd test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  e2etest:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: false
          file: test.Dockerfile
